[package]
name = "repl-vision"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
image.workspace = true
log.workspace = true
repl-capture.workspace = true
repl-core.workspace = true
serde = { workspace = true }
serde_json.workspace = true
thiserror.workspace = true
